version: '2'
services:
  ssclient:
    image: lonelyleaf/ss-stack-shadowsocks-client:0.3
    ports:
      - 1080:1080
    restart: always
    volumes:
      #- ./configs/sslocal-config.json:/etc/sslocal.json
      - ./configs/sslocal-kcp-config.json:/etc/sslocal.json
    command: "-c /etc/sslocal.json"
    depends_on:
      - kcptun
  privoxy:
    image: lonelyleaf/ss-stack-privoxy:0.2
    ports:
      - 2080:2080
    restart: always
    volumes:
      - ./configs/privoxy.config:/etc/privoxy/privoxy.config
    depends_on:
      - ssclient
  kcptun:
    image: lonelyleaf/ss-stack-kcp-client:0.2
    command: "-c /etc/kcp.json"
    restart: always
    volumes:
      - ./configs/kcp-config.json:/etc/kcp.json