apiVersion: v1
kind: Service
metadata:
  name: kcptun
  namespace: ss-stack
spec:
  ports:
    - port: 8388
  selector:
    app: kcp
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kcptun
  namespace: ss-stack
spec:
  template:
    metadata:
      labels:
        app: kcp
    spec:
      containers:
        - name: kcptun
          image: xtaci/kcptun
          command:
            - /bin/sh
            - -c
          args:
            - cat /tmp/tmp-kcp.json > /etc/kcp.json && /bin/client -c /etc/kcp.json
          securityContext:
            runAsUser: 0
          readinessProbe:
            periodSeconds: 5
            initialDelaySeconds: 10
            tcpSocket:
              port: 8388
          livenessProbe:
            periodSeconds: 5
            initialDelaySeconds: 10
            tcpSocket:
              port: 8388
          ports:
            - containerPort: 8388
              name: kcp-port
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: kcp-config
      restartPolicy: Always
      volumes:
        - name: kcp-config
          configMap:
            name: ss-stack-config
            items:
              - key: kcp.json
                path: tmp-kcp.json

---



