apiVersion: v1
kind: Service
metadata:
  name: ss-client
  namespace: ss-stack
spec:
  ports:
    - port: 1080
      targetPort: 1080
      protocol: TCP
  selector:
    app: ss-client
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ss-client
  namespace: ss-stack
spec:
  template:
    metadata:
      labels:
        app: ss-client
    spec:
      containers:
        - name: ssclient
          args:
            - cat /tmp/tmp-sslocal.json > /etc/sslocal.json && ss-local -c /etc/sslocal.json
          command:
            - /bin/sh
            - -c
          image: shadowsocks/shadowsocks-libev:v3.2.4
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
          readinessProbe:
            periodSeconds: 5
            initialDelaySeconds: 10
            tcpSocket:
              port: 1080
          livenessProbe:
            periodSeconds: 5
            initialDelaySeconds: 10
            tcpSocket:
              port: 1080
          ports:
            - containerPort: 1080
              protocol: TCP
              name: socket5-proxy
          volumeMounts:
            - mountPath: /tmp/
              name: ss-config
      restartPolicy: Always
      volumes:
        - name: ss-config
          configMap:
            name: ss-stack-config
            items:
              - key: sslocal.json
                path: tmp-sslocal.json