apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ss-stack-config
      namespace: ss-stack
    data:
      kcp.json: |-
        {
          "localaddr": ":8388",
          "remoteaddr": "远程服务器地址",
          "mode": "fast2",
          "conn": 1,
          "autoexpire": 60,
          "mtu": 1350,
          "sndwnd": 1024,
          "rcvwnd": 1024,
          "datashard": 10,
          "parityshard": 3,
          "dscp": 0,
          "nocomp": false,
          "acknodelay": false,
          "nodelay": 0,
          "interval": 20,
          "resend": 2,
          "nc": 1,
          "sockbuf": 4194304,
          "keepalive": 10
        }
      privoxy.config: |-
        forward-socks5 / ssclient:1080 .
        listen-address 0.0.0.0:2080
      sslocal.json: |-
        {
          "server": "kcptun",
          "server_port": 8388,
          "method": "chacha20",
          "password": "ss密码",
          "fast_open": false,
          "local_address": "0.0.0.0",
          "local_port": 1080,
          "workers": 2
        }
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: kcptun
      namespace: ss-stack
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: kcptun
              args:
                - cat /tmp/tmp-kcp.json > /etc/kcp.json && /bin/client -c /etc/kcp.json
              command:
                - /bin/sh
                - -c
              image: xtaci/kcptun
              imagePullPolicy: Always
              securityContext:
                runAsUser: 0
              volumeMounts:
                - mountPath: /tmp
                  name: kcp-config
          restartPolicy: Always
          volumes:
            - name: kcp-config
              configMap:
                name: ss-stack-config
                items:
                  - key: kcp.json
                    path: tmp-kcp.json
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: privoxy
      namespace: ss-stack
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: privoxy
              image: lonelyleaf/ss-stack-privoxy:1.0
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /etc/privoxy
                  name: privoxy-config
          volumes:
            - name: privoxy-config
              configMap:
                name: ss-stack-config
                items:
                  - key: privoxy.config
                    path: privoxy.config
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: ssclient
      namespace: ss-stack
    spec:
      template:
        spec:
          containers:
            - name: ssclient
              args:
                - cat /tmp/tmp-sslocal.json > /etc/sslocal.json && ss-local -c /etc/sslocal.json
              command:
                - /bin/sh
                - -c
              image: shadowsocks/shadowsocks-libev:v3.2.4
              imagePullPolicy: Always
              securityContext:
                runAsUser: 0
              tty: true
              volumeMounts:
                - mountPath: /tmp/
                  name: ss-config
          restartPolicy: Always
          volumes:
            - name: ss-config
              configMap:
                name: ss-stack-config
                items:
                  - key: sslocal.json
                    path: tmp-sslocal.json